[package]
name = "pdf3d"
description = "Extraction of 3D streams (U3D, PRC, glTF) into a normalized Scene."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
