// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tauri-specta from crates/app. Do not edit by hand:
// run `pnpm gen:bindings` instead.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
};

/* Types */
/**  Static information about the application, shown in the About screen. */
export type AppInfo = {
	name: string,
	version: string,
	license: string,
	/**  Public source code repository, linked from the UI as the AGPL requires. */
	sourceUrl: string,
};

