// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tauri-specta from crates/app. Do not edit by hand:
// run `pnpm gen:bindings` instead.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  Opens a document and starts streaming its tiles over `tiles` as soon as a
	 *  viewport is set. Parsing runs on a blocking thread, never on the UI thread.
	 */
	openDocument: (path: string, password: string | null, tiles: Channel<ArrayBuffer>) => typedError<OpenedDocument, DocumentError>(__TAURI_INVOKE("open_document", { path, password, tiles })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,info:({...v.data.info,pages:v.data.info.pages.map(i=>i)}),viewState:v.data.viewState==null?v.data.viewState:v.data.viewState}) } : v) as typeof v)),
	/**  Tells the renderer what is on screen; it decides which tiles to send. */
	setViewport: (id: number, viewport: Viewport) => typedError<null, DocumentError>(__TAURI_INVOKE("set_viewport", { id, viewport })),
	closeDocument: (id: number) => typedError<null, DocumentError>(__TAURI_INVOKE("close_document", { id })),
	/**  Remembers where the user is in a document (called debounced by the UI). */
	saveViewState: (id: number, state: ViewState) => typedError<null, DocumentError>(__TAURI_INVOKE("save_view_state", { id, state })),
	/**  Files passed on the command line, to open at startup. */
	startupFiles: () => __TAURI_INVOKE<string[]>("startup_files"),
	/**  Recently opened documents that still exist, newest first. */
	recentDocuments: () => typedError<RecentDocument[], DocumentError>(__TAURI_INVOKE("recent_documents")),
	/**  Removes a document from the recent list. */
	forgetDocument: (path: string) => typedError<null, DocumentError>(__TAURI_INVOKE("forget_document", { path })),
};

/* Types */
/**  Static information about the application, shown in the About screen. */
export type AppInfo = {
	name: string,
	version: string,
	license: string,
	/**  Public source code repository, linked from the UI as the AGPL requires. */
	sourceUrl: string,
};

/**  Errors shown to the user. Messages never include passwords. */
export type DocumentError = { kind: "notFound" } | { kind: "passwordRequired" } | { kind: "wrongPassword" } | { kind: "empty" } | { kind: "invalid"; detail: string } | { kind: "io"; detail: string } | { kind: "unknownDocument" } | { kind: "internal"; detail: string };

/**  Everything the UI needs to lay out a document before rendering anything. */
export type DocumentInfo = {
	pages: PageSize[],
	metadata: Metadata,
	/**  Pages whose box could not be read; shown with a fallback size. */
	brokenPages: number[],
	/**
	 *  Pages `0..measured_pages` have exact sizes; later ones are estimates
	 *  (the last measured size) until measured.
	 */
	measuredPages: number,
};

export type FitMode = "width" | "page" | "free";

export type Metadata = {
	title: string | null,
	author: string | null,
	subject: string | null,
	creator: string | null,
	producer: string | null,
	/**  For example `PDF 1.7`. */
	format: string | null,
};

export type OpenedDocument = {
	id: number,
	path: string,
	fileName: string,
	info: DocumentInfo,
	/**  Where the user left this document last time, if known. */
	viewState: ViewState | null,
};

/**  A rectangle in page points (origin top-left, y down, as MuPDF uses). */
export type PageRect = {
	x0: number,
	y0: number,
	x1: number,
	y1: number,
};

/**  Part of a page, in points, that the frontend wants rendered at `level`. */
export type PageRegion = {
	page: number,
	rect: PageRect,
	level: ZoomLevel,
};

/**  Size of a page in PDF points (1/72 inch), rotation already applied. */
export type PageSize = {
	width: number,
	height: number,
};

/**  A document the user opened before, for the start screen. */
export type RecentDocument = {
	path: string,
	fileName: string,
	/**  Zero-based page where the user left off. */
	page: number,
	pageCount: number | null,
	/**
	 *  Seconds since the Unix epoch (u32 is enough until 2106 and stays
	 *  a plain JS number).
	 */
	lastOpened: number,
};

/**  Identifies one tile of one page at one zoom level. */
export type TileKey = {
	page: number,
	level: ZoomLevel,
	x: number,
	y: number,
};

export type ViewState = {
	/**  Page at the top of the window. */
	page: number,
	/**  How far into that page the top of the window is, from 0 to 1. */
	pageOffset: number,
	/**  Horizontal scroll as a fraction of the scrollable width, from 0 to 1. */
	scrollX: number,
	/**  Zoom where 1 = 100 % (1 pt = 1/72 in at 96 dpi). */
	zoom: number,
	fit: FitMode,
};

/**
 *  What the frontend currently shows. The backend decides which tiles that
 *  needs; the frontend only describes geometry (AGENTS.md §4).
 */
export type Viewport = {
	/**  On-screen regions, most important first. */
	visible: PageRegion[],
	/**
	 *  Off-screen regions likely to be shown next (in scroll direction first),
	 *  typically at a lower level so they are cheap to prefetch.
	 */
	nearby: PageRegion[],
	/**
	 *  Tiles the frontend dropped since the last viewport; they will be sent
	 *  again if needed.
	 */
	evicted: TileKey[],
};

/**  Discrete zoom level; level `l` renders at `sqrt(2)^l` device pixels per point. */
export type ZoomLevel = number;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

