// SPDX-License-Identifier: AGPL-3.0-or-later

//! Tauri shell of the PDF reader. Heavy lifting lives in the Tauri-free crates.

mod commands;
mod documents;
mod view_state;

use tauri::Manager;
use tauri_specta::{Builder, collect_commands};
use tracing_subscriber::EnvFilter;

/// Path of the generated TypeScript bindings, relative to this crate.
pub const BINDINGS_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../ui/src/bindings.ts");

const BINDINGS_HEADER: &str = "// SPDX-License-Identifier: AGPL-3.0-or-later\n\
// Generated by tauri-specta from crates/app. Do not edit by hand:\n\
// run `pnpm gen:bindings` instead.\n";

/// Every IPC command exposed to the frontend. Registering a command here is
/// what makes it both callable and present in the generated bindings.
pub fn specta_builder() -> Builder<tauri::Wry> {
    // Floats crossing IPC are always finite here (Rust validates them and JSON
    // cannot carry NaN from JS), so export them as `number`, not `number | null`.
    let floats = specta_typescript::semantic::Configuration::default().enable_lossless_floats();
    Builder::<tauri::Wry>::new()
        .semantic_types(floats)
        .commands(collect_commands![
            commands::app_info,
            documents::open_document,
            documents::set_viewport,
            documents::set_layer,
            documents::close_document,
            documents::save_view_state,
            documents::startup_files,
            documents::recent_documents,
            documents::forget_document,
        ])
}

/// Writes the TypeScript bindings for the IPC commands to [`BINDINGS_PATH`].
pub fn export_bindings() -> Result<(), specta_typescript::Error> {
    specta_builder().export(
        specta_typescript::Typescript::default().header(BINDINGS_HEADER),
        BINDINGS_PATH,
    )
}

/// Starts the desktop application and blocks until it exits.
pub fn run() -> tauri::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .init();

    let builder = specta_builder();
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .manage(documents::Documents::default())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let dir = app.path().app_data_dir()?;
            app.manage(view_state::ViewStates::new(dir.join("view-states.json")));
            Ok(())
        })
        .run(tauri::generate_context!())
}

#[cfg(test)]
mod tests {
    /// Regenerates `ui/src/bindings.ts`. CI fails if the result differs from
    /// the committed file, so bindings can never drift from the Rust types.
    #[test]
    fn export_bindings() {
        super::export_bindings().unwrap();
    }
}
