// SPDX-License-Identifier: AGPL-3.0-or-later

//! Tauri shell of the PDF reader. Heavy lifting lives in the Tauri-free crates.

mod commands;

use tauri_specta::{Builder, collect_commands};
use tracing_subscriber::EnvFilter;

/// Path of the generated TypeScript bindings, relative to this crate.
pub const BINDINGS_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../ui/src/bindings.ts");

const BINDINGS_HEADER: &str = "// SPDX-License-Identifier: AGPL-3.0-or-later\n\
// Generated by tauri-specta from crates/app. Do not edit by hand:\n\
// run `pnpm gen:bindings` instead.\n";

/// Every IPC command exposed to the frontend. Registering a command here is
/// what makes it both callable and present in the generated bindings.
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![commands::app_info])
}

/// Writes the TypeScript bindings for the IPC commands to [`BINDINGS_PATH`].
pub fn export_bindings() -> Result<(), specta_typescript::Error> {
    specta_builder().export(
        specta_typescript::Typescript::default().header(BINDINGS_HEADER),
        BINDINGS_PATH,
    )
}

/// Starts the desktop application and blocks until it exits.
pub fn run() -> tauri::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .init();

    let builder = specta_builder();
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
}

#[cfg(test)]
mod tests {
    /// Regenerates `ui/src/bindings.ts`. CI fails if the result differs from
    /// the committed file, so bindings can never drift from the Rust types.
    #[test]
    fn export_bindings() {
        super::export_bindings().unwrap();
    }
}
